TenantAccount/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TenantAccount.Data;
using TenantAccount.Data.Entities;
using System.Security.Claims;

namespace TenantAccount.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public MessagesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var messages = _context.Messages.Include(s => s.IdentityUser).ToList();
            return View(messages);
        }

        public IActionResult Create(string userId)
        {
            var user = _userManager.FindByIdAsync(userId).GetAwaiter().GetResult();
            var message = new Message { IdentityUser = user };
            return View(message);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Message message)
        {
            if (ModelState.IsValid)
            {
                var user = _userManager.FindByIdAsync(message.IdentityUser.Id).GetAwaiter().GetResult();
                message.IdentityUser = user;

                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(message);
        }

        public IActionResult UserMesseges()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var messages = _context.Messages.Include(s => s.IdentityUser).Where(s => s.IdentityUser.Id == userId).ToList();

            return View(messages);
        }

        public IActionResult Read(int id)
        {
            var message = _context.Messages.FirstOrDefault(s => s.Id == id);

            if (message != null)
            {
                message.Read = 1;
                _context.SaveChanges();
            }

            return RedirectToAction("UserMesseges");
        }
    }
}

TenantAccount/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TenantAccount.Data;
using TenantAccount.Data.Entities;

namespace TenantAccount.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProfilesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var viewData = new Profile();

            try
            {
                var dataContext = await _context.Profiles.FirstOrDefaultAsync(s => s.IdentityUser.Id == userId);

                if(dataContext != null)
                {
                    viewData = dataContext;
                }
            }
            catch (Exception ex) {
            }

            return View(viewData);
        }

        public async Task<IActionResult> AllProfil()
        {
            var dataContext = await _context.Profiles.Include(s => s.IdentityUser).ToListAsync();
            return View(dataContext);
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Profile profile)
        {
            IdentityUser user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                profile.IdentityUser = user;

                _context.Add(profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Profile profile)
        {
            if (id != profile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Profiles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Profiles'  is null.");
            }
            var profile = await _context.Profiles.FindAsync(id);
            if (profile != null)
            {
                _context.Profiles.Remove(profile);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfileExists(int id)
        {
          return (_context.Profiles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TenantAccount/Controllers/СontractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TenantAccount.Data;
using TenantAccount.Data.Entities;

namespace TenantAccount.Controllers
{
    [Authorize]
    public class ContractController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ContractController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Сontract
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var applicationDbContext = new List<Сontract>();

            if (!User.IsInRole("admin"))
            {
                applicationDbContext = await _context.Сontracts.Include(с => с.Status).Where(s => s.IdentityUser.Id == userId).ToListAsync();
            }
            else
            {
                applicationDbContext = await _context.Сontracts.Include(с => с.Status).ToListAsync();
            }

            return View(applicationDbContext);
        }

        // GET: Сontract/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Сontracts == null)
            {
                return NotFound();
            }

            var сontract = await _context.Сontracts
                .Include(с => с.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (сontract == null)
            {
                return NotFound();
            }

            return View(сontract);
        }

        // GET: Сontract/Create
        public IActionResult Create()
        {
            ViewData["StatusId"] = new SelectList(_context.СontractStatuses, "Id", "Name");
            return View();
        }

        // POST: Сontract/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Сontract сontract)
        {
            IdentityUser user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                сontract.IdentityUser = user;

                _context.Add(сontract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.СontractStatuses, "Id", "Name", сontract.StatusId);
            return View(сontract);
        }

        // GET: Сontract/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Сontracts == null)
            {
                return NotFound();
            }

            var сontract = await _context.Сontracts.FindAsync(id);
            if (сontract == null)
            {
                return NotFound();
            }
            ViewData["StatusId"] = new SelectList(_context.СontractStatuses, "Id", "Name", сontract.StatusId);
            return View(сontract);
        }

        // POST: Сontract/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Сontract сontract)
        {
            if (id != сontract.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(сontract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!СontractExists(сontract.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.СontractStatuses, "Id", "Name", сontract.StatusId);
            return View(сontract);
        }

        // GET: Сontract/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Сontracts == null)
            {
                return NotFound();
            }

            var сontract = await _context.Сontracts
                .Include(с => с.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (сontract == null)
            {
                return NotFound();
            }

            return View(сontract);
        }

        // POST: Сontract/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Сontracts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Сontracts'  is null.");
            }
            var сontract = await _context.Сontracts.FindAsync(id);
            if (сontract != null)
            {
                _context.Сontracts.Remove(сontract);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool СontractExists(int id)
        {
          return (_context.Сontracts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TenantAccount/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TenantAccount</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TenantAccount.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TenantAccount</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contract" asp-action="Index">Договора</a>
                            </li>

                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ContractStatus" asp-action="Index">Статусы Договора</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/UserConfirmation" >Все пользователи</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="AllProfil">Все арендодатели</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index">Все сообщения</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="UserMesseges">Все сообщения</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="Index">Профиль</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TenantAccount - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>